# Version of config file
version: 1.2.0

# Server's listening port (default: 7054)
port: 7054

# Enables debug logging (default: false)
debug: false

# Size limit of an acceptable CRL in bytes (default: 512000)
crlsizelimit: 512000

# TLS section for the server's listening port
tls:
  # Enable TLS (default: false)
  enabled: true
  # TLS for the server's listening port
  certfile: /etc/hyperledger/fabric-ca-server-config/ca.moe.com-cert.pem
  keyfile: /etc/hyperledger/fabric-ca-server-config/ca.moe.com-key.pem
  clientauth:
    type: noclientcert

# The CA section contains information related to the Certificate Authority
ca:
  # Name of this CA
  name: ca.moe.com
  # Key file (is only used to import a private key into BCCSP)
  keyfile: /etc/hyperledger/fabric-ca-server-config/ca.moe.com-key.pem
  # Certificate file (default: ca-cert.pem)
  certfile: /etc/hyperledger/fabric-ca-server-config/ca.moe.com-cert.pem
  # Chain file
  chainfile: /etc/hyperledger/fabric-ca-server-config/ca-chain.moe.com.pem

# The gencrl REST endpoint is used to generate a CRL that contains revoked certificates
crl:
  expiry: 24h

# Registry section controls how the fabric-ca-server does two things:
registry:
  # Maximum number of times a password/secret can be reused for enrollment (default: -1, which means there is no limit)
  maxenrollments: -1
  # Contains identity information which is used when LDAP is disabled
  identities:
     - name: admin
       pass: adminpw
       type: client
       affiliation: ""
       attrs:
          hf.Registrar.Roles: "*"
          hf.Registrar.DelegateRoles: "*"
          hf.Revoker: true
          hf.IntermediateCA: true
          hf.GenCRL: true
          hf.Registrar.Attributes: "*"
          hf.AffiliationMgr: true

# Database section
db:
  type: sqlite3
  datasource: fabric-ca-server.db
  tls:
    enabled: false

# Signing section
signing:
  default:
    usage:
      - digital signature
    expiry: 8760h
  profiles:
    ca:
      usage:
        - cert sign
        - crl sign
      expiry: 43800h
      caconstraint:
        isca: true
        maxpathlen: 0
    tls:
      usage:
        - signing
        - key encipherment
        - server auth
        - client auth
        - key agreement
      expiry: 8760h

# Certificate Signing Request (CSR) section
csr:
  cn: ca.moe.com
  names:
    - C: US
      ST: "New York"
      L: "New York"
      O: moe.com
      OU:
  hosts:
    - localhost
    - ca.moe.com
  ca:
    expiry: 131400h
    pathlength: 1

# BCCSP section
bccsp:
  default: SW
  sw:
    hash: SHA2
    security: 256
    filekeystore:
      keystore: msp/keystore

# Multi CA section
cacount:

cafiles:

# Intermediate CA section
intermediate:
  parentserver:
    url:
    caname:
  enrollment:
    hosts:
    profile:
    label:
  tls:
    certfiles:
    client:
      certfile:
      keyfile:
