# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

networks:
  test:
    name: fabric_test

services:
# ----------------------------------------------------------
#                 Entidad Certificadora CA
# ----------------------------------------------------------
  ca_cne:
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-cne
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    ports:
      - "7054:7054"
      - "17054:17054"
    volumes:
      - ../organizations/fabric-ca/cne:/etc/hyperledger/fabric-ca-server
    container_name: ca_cne
    networks:
      - test

  ca_moe:
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-moe
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
    ports:
      - "8054:8054"
      - "18054:18054"
    volumes:
      - ../organizations/fabric-ca/moe:/etc/hyperledger/fabric-ca-server
    container_name: ca_moe
    networks:
      - test

  ca_cne_orderer:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-cne-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7055
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17055
    ports:
      - "7055:7055"
      - "17055:17055"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/ordererCne:/etc/hyperledger/fabric-ca-server
    container_name: ca_cne_orderer
    networks:
      - test

  ca_moe_orderer:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-moe-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8055
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18055
    ports:
      - "8055:8055"
      - "18055:18055"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/ordererMoe:/etc/hyperledger/fabric-ca-server
    container_name: ca_moe_orderer
    networks:
      - test

  # ca_org1:
  #   image: hyperledger/fabric-ca:latest
  #   labels:
  #     service: hyperledger-fabric
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca-org1
  #     - FABRIC_CA_SERVER_TLS_ENABLED=true
  #     - FABRIC_CA_SERVER_PORT=7054
  #     - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
  #   ports:
  #     - "7054:7054"
  #     - "17054:17054"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
  #   volumes:
  #     - ../organizations/fabric-ca/org1:/etc/hyperledger/fabric-ca-server
  #   container_name: ca_org1
  #   networks:
  #     - test

  # ca_org2:
  #   image: hyperledger/fabric-ca:latest
  #   labels:
  #     service: hyperledger-fabric
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca-org2
  #     - FABRIC_CA_SERVER_TLS_ENABLED=true
  #     - FABRIC_CA_SERVER_PORT=8054
  #     - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
  #   ports:
  #     - "8054:8054"
  #     - "18054:18054"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
  #   volumes:
  #     - ../organizations/fabric-ca/org2:/etc/hyperledger/fabric-ca-server
  #   container_name: ca_org2
  #   networks:
  #     - test

  # ca_orderer:
  #   image: hyperledger/fabric-ca:latest
  #   labels:
  #     service: hyperledger-fabric
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca-orderer
  #     - FABRIC_CA_SERVER_TLS_ENABLED=true
  #     - FABRIC_CA_SERVER_PORT=9054
  #     - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:19054
  #   ports:
  #     - "9054:9054"
  #     - "19054:19054"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
  #   volumes:
  #     - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
  #   container_name: ca_orderer
  #   networks:
  #     - test
